# Generated by Django 5.1.4 on 2025-01-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Publicacion',
                'db_table': 'publicacion',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Article2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('publications', models.ManyToManyField(to='pruebamod2.publication')),
            ],
            options={
                'verbose_name': 'Articulo2',
                'db_table': 'articulo2',
                'ordering': ['headline'],
            },
        ),
    ]
